# freecad-python generated by Parametrix
# run the script with:
# freecad.cmd myScript.py

import FreeCAD as App
import Part

#print(sys.argv)
outFileName = "gear_wheel"
if (len(sys.argv) == 3):
    outFileName = sys.argv[2]
print(f"outFileName: {outFileName}")

def ctr_face_gear_wheel_teethProfile_Fa0_Ctr0():
	P000 = App.Vector(74.3343, -3.2263, 0)
	P001 = App.Vector(74.9295, -3.2522, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(75.8765, -3.2319, 0)
	P003 = App.Vector(76.8129, -3.0894, 0)
	S001 = Part.Arc(P001, P002, P003)
	P004 = App.Vector(78.6441, -2.6252, 0)
	P005 = App.Vector(80.4414, -2.0436, 0)
	S002 = Part.Arc(P003, P004, P005)
	P006 = App.Vector(83.9225, -0.5745, 0)
	P007 = App.Vector(87.2249, 1.2613, 0)
	S003 = Part.Arc(P005, P006, P007)
	P008 = App.Vector(91.1080, 3.9439, 0)
	P009 = App.Vector(94.7453, 6.9515, 0)
	S004 = Part.Arc(P007, P008, P009)
	P010 = App.Vector(94.4094, 10.5763, 0)
	S005 = Part.LineSegment(P009, P010)
	P011 = App.Vector(90.2814, 12.8643, 0)
	P012 = App.Vector(85.9715, 14.7877, 0)
	S006 = Part.Arc(P010, P011, P012)
	P013 = App.Vector(82.3880, 15.9854, 0)
	P014 = App.Vector(78.6963, 16.7899, 0)
	S007 = Part.Arc(P012, P013, P014)
	P015 = App.Vector(76.8227, 17.0313, 0)
	P016 = App.Vector(74.9374, 17.1511, 0)
	S008 = Part.Arc(P014, P015, P016)
	P017 = App.Vector(73.9907, 17.1191, 0)
	P018 = App.Vector(73.0561, 16.9651, 0)
	S009 = Part.Arc(P016, P017, P018)
	P019 = App.Vector(72.4758, 16.8303, 0)
	S010 = Part.LineSegment(P018, P019)
	P020 = App.Vector(71.0076, 17.0556, 0)
	P021 = App.Vector(70.0997, 18.2311, 0)
	S011 = Part.Arc(P019, P020, P021)
	P022 = App.Vector(69.1974, 21.4023, 0)
	S012 = Part.LineSegment(P021, P022)
	P023 = App.Vector(69.3505, 22.8797, 0)
	P024 = App.Vector(70.4802, 23.8442, 0)
	S013 = Part.Arc(P022, P023, P024)
	P025 = App.Vector(71.0445, 24.0351, 0)
	S014 = Part.LineSegment(P024, P025)
	P026 = App.Vector(71.9202, 24.3961, 0)
	P027 = App.Vector(72.7419, 24.8673, 0)
	S015 = Part.Arc(P025, P026, P027)
	P028 = App.Vector(74.2818, 25.9616, 0)
	P029 = App.Vector(75.7476, 27.1532, 0)
	S016 = Part.Arc(P027, P028, P029)
	P030 = App.Vector(78.4629, 29.7806, 0)
	P031 = App.Vector(80.8791, 32.6854, 0)
	S017 = Part.Arc(P029, P030, P031)
	P032 = App.Vector(83.5310, 36.5896, 0)
	P033 = App.Vector(85.8362, 40.7080, 0)
	S018 = Part.Arc(P031, P032, P033)
	P034 = App.Vector(84.2136, 43.9667, 0)
	S019 = Part.LineSegment(P033, P034)
	P035 = App.Vector(79.5378, 44.6090, 0)
	P036 = App.Vector(74.8241, 44.8456, 0)
	S020 = Part.Arc(P034, P035, P036)
	P037 = App.Vector(71.0499, 44.6679, 0)
	P038 = App.Vector(67.3169, 44.0845, 0)
	S021 = Part.Arc(P036, P037, P038)
	P039 = App.Vector(65.4826, 43.6328, 0)
	P040 = App.Vector(63.6813, 43.0634, 0)
	S022 = Part.Arc(P038, P039, P040)
	P041 = App.Vector(62.8101, 42.6916, 0)
	P042 = App.Vector(61.9943, 42.2103, 0)
	S023 = Part.Arc(P040, P041, P042)
	P043 = App.Vector(61.5018, 41.8751, 0)
	S024 = Part.LineSegment(P042, P043)
	P044 = App.Vector(60.0515, 41.5548, 0)
	P045 = App.Vector(58.7802, 42.3230, 0)
	S025 = Part.Arc(P043, P044, P045)
	P046 = App.Vector(56.7933, 44.9541, 0)
	S026 = Part.LineSegment(P045, P046)
	P047 = App.Vector(56.4023, 46.3870, 0)
	P048 = App.Vector(57.1073, 47.6944, 0)
	S027 = Part.Arc(P046, P047, P048)
	P049 = App.Vector(57.5645, 48.0763, 0)
	S028 = Part.LineSegment(P048, P049)
	P050 = App.Vector(58.2507, 48.7293, 0)
	P051 = App.Vector(58.8467, 49.4655, 0)
	S029 = Part.Arc(P049, P050, P051)
	P052 = App.Vector(59.8873, 51.0421, 0)
	P053 = App.Vector(60.8237, 52.6828, 0)
	S030 = Part.Arc(P051, P052, P053)
	P054 = App.Vector(62.4065, 56.1137, 0)
	P055 = App.Vector(63.6102, 59.6952, 0)
	S031 = Part.Arc(P053, P054, P055)
	P056 = App.Vector(64.6726, 64.2937, 0)
	P057 = App.Vector(65.3345, 68.9667, 0)
	S032 = Part.Arc(P055, P056, P057)
	P058 = App.Vector(62.6442, 71.4192, 0)
	S033 = Part.LineSegment(P057, P058)
	P059 = App.Vector(58.0522, 70.3290, 0)
	P060 = App.Vector(53.5713, 68.8468, 0)
	S034 = Part.Arc(P058, P059, P060)
	P061 = App.Vector(50.1162, 67.3178, 0)
	P062 = App.Vector(46.8460, 65.4252, 0)
	S035 = Part.Arc(P060, P061, P062)
	P063 = App.Vector(45.2987, 64.3414, 0)
	P064 = App.Vector(43.8248, 63.1598, 0)
	S036 = Part.Arc(P062, P063, P064)
	P065 = App.Vector(43.1467, 62.4984, 0)
	P066 = App.Vector(42.5598, 61.7549, 0)
	S037 = Part.Arc(P064, P065, P066)
	P067 = App.Vector(42.2217, 61.2644, 0)
	S038 = Part.LineSegment(P066, P067)
	P068 = App.Vector(40.9850, 60.4418, 0)
	P069 = App.Vector(39.5221, 60.6989, 0)
	S039 = Part.Arc(P067, P068, P069)
	P070 = App.Vector(36.7189, 62.4345, 0)
	S040 = Part.LineSegment(P069, P070)
	P071 = App.Vector(35.8367, 63.6295, 0)
	P072 = App.Vector(36.0218, 65.1032, 0)
	S041 = Part.Arc(P070, P071, P072)
	P073 = App.Vector(36.3102, 65.6245, 0)
	S042 = Part.LineSegment(P072, P073)
	P074 = App.Vector(36.7141, 66.4813, 0)
	P075 = App.Vector(37.0039, 67.3831, 0)
	S043 = Part.Arc(P073, P074, P075)
	P076 = App.Vector(37.4047, 69.2292, 0)
	P077 = App.Vector(37.6852, 71.0973, 0)
	S044 = Part.Arc(P075, P076, P077)
	P078 = App.Vector(37.9217, 74.8683, 0)
	P079 = App.Vector(37.7504, 78.6427, 0)
	S045 = Part.Arc(P077, P078, P079)
	P080 = App.Vector(37.0799, 83.3145, 0)
	P081 = App.Vector(36.0089, 87.9111, 0)
	S046 = Part.Arc(P079, P080, P081)
	P082 = App.Vector(32.6144, 89.2261, 0)
	S047 = Part.LineSegment(P081, P082)
	P083 = App.Vector(28.7263, 86.5507, 0)
	P084 = App.Vector(25.0834, 83.5499, 0)
	S048 = Part.Arc(P082, P083, P084)
	P085 = App.Vector(22.4139, 80.8760, 0)
	P086 = App.Vector(20.0483, 77.9299, 0)
	S049 = Part.Arc(P084, P085, P086)
	P087 = App.Vector(18.9970, 76.3603, 0)
	P088 = App.Vector(18.0494, 74.7261, 0)
	S050 = Part.Arc(P086, P087, P088)
	P089 = App.Vector(17.6561, 73.8644, 0)
	P090 = App.Vector(17.3774, 72.9591, 0)
	S051 = Part.Arc(P088, P089, P090)
	P091 = App.Vector(17.2394, 72.3796, 0)
	S052 = Part.LineSegment(P090, P091)
	P092 = App.Vector(16.3833, 71.1658, 0)
	P093 = App.Vector(14.9263, 70.8770, 0)
	S053 = Part.Arc(P091, P092, P093)
	P094 = App.Vector(11.6854, 71.4828, 0)
	S054 = Part.LineSegment(P093, P094)
	P095 = App.Vector(10.4311, 72.2784, 0)
	P096 = App.Vector(10.0713, 73.7195, 0)
	S055 = Part.Arc(P094, P095, P096)
	P097 = App.Vector(10.1519, 74.3097, 0)
	S056 = Part.LineSegment(P096, P097)
	P098 = App.Vector(10.2191, 75.2546, 0)
	P099 = App.Vector(10.1636, 76.2002, 0)
	S057 = Part.Arc(P097, P098, P099)
	P100 = App.Vector(9.8704, 78.0664, 0)
	P101 = App.Vector(9.4571, 79.9097, 0)
	S058 = Part.Arc(P099, P100, P101)
	P102 = App.Vector(8.3154, 83.5115, 0)
	P103 = App.Vector(6.7921, 86.9692, 0)
	S059 = Part.Arc(P101, P102, P103)
	P104 = App.Vector(4.4793, 91.0833, 0)
	P105 = App.Vector(1.8202, 94.9826, 0)
	S060 = Part.Arc(P103, P104, P105)
	P106 = App.Vector(-1.8202, 94.9826, 0)
	S061 = Part.LineSegment(P105, P106)
	P107 = App.Vector(-4.4793, 91.0833, 0)
	P108 = App.Vector(-6.7921, 86.9692, 0)
	S062 = Part.Arc(P106, P107, P108)
	P109 = App.Vector(-8.3154, 83.5115, 0)
	P110 = App.Vector(-9.4571, 79.9097, 0)
	S063 = Part.Arc(P108, P109, P110)
	P111 = App.Vector(-9.8704, 78.0664, 0)
	P112 = App.Vector(-10.1636, 76.2002, 0)
	S064 = Part.Arc(P110, P111, P112)
	P113 = App.Vector(-10.2191, 75.2546, 0)
	P114 = App.Vector(-10.1519, 74.3097, 0)
	S065 = Part.Arc(P112, P113, P114)
	P115 = App.Vector(-10.0713, 73.7195, 0)
	S066 = Part.LineSegment(P114, P115)
	P116 = App.Vector(-10.4311, 72.2784, 0)
	P117 = App.Vector(-11.6854, 71.4828, 0)
	S067 = Part.Arc(P115, P116, P117)
	P118 = App.Vector(-14.9263, 70.8770, 0)
	S068 = Part.LineSegment(P117, P118)
	P119 = App.Vector(-16.3833, 71.1658, 0)
	P120 = App.Vector(-17.2394, 72.3796, 0)
	S069 = Part.Arc(P118, P119, P120)
	P121 = App.Vector(-17.3774, 72.9591, 0)
	S070 = Part.LineSegment(P120, P121)
	P122 = App.Vector(-17.6561, 73.8644, 0)
	P123 = App.Vector(-18.0494, 74.7261, 0)
	S071 = Part.Arc(P121, P122, P123)
	P124 = App.Vector(-18.9970, 76.3603, 0)
	P125 = App.Vector(-20.0483, 77.9299, 0)
	S072 = Part.Arc(P123, P124, P125)
	P126 = App.Vector(-22.4139, 80.8760, 0)
	P127 = App.Vector(-25.0834, 83.5499, 0)
	S073 = Part.Arc(P125, P126, P127)
	P128 = App.Vector(-28.7263, 86.5507, 0)
	P129 = App.Vector(-32.6144, 89.2261, 0)
	S074 = Part.Arc(P127, P128, P129)
	P130 = App.Vector(-36.0089, 87.9111, 0)
	S075 = Part.LineSegment(P129, P130)
	P131 = App.Vector(-37.0799, 83.3145, 0)
	P132 = App.Vector(-37.7504, 78.6427, 0)
	S076 = Part.Arc(P130, P131, P132)
	P133 = App.Vector(-37.9217, 74.8683, 0)
	P134 = App.Vector(-37.6852, 71.0973, 0)
	S077 = Part.Arc(P132, P133, P134)
	P135 = App.Vector(-37.4047, 69.2292, 0)
	P136 = App.Vector(-37.0039, 67.3831, 0)
	S078 = Part.Arc(P134, P135, P136)
	P137 = App.Vector(-36.7141, 66.4813, 0)
	P138 = App.Vector(-36.3102, 65.6245, 0)
	S079 = Part.Arc(P136, P137, P138)
	P139 = App.Vector(-36.0218, 65.1032, 0)
	S080 = Part.LineSegment(P138, P139)
	P140 = App.Vector(-35.8367, 63.6295, 0)
	P141 = App.Vector(-36.7189, 62.4345, 0)
	S081 = Part.Arc(P139, P140, P141)
	P142 = App.Vector(-39.5221, 60.6989, 0)
	S082 = Part.LineSegment(P141, P142)
	P143 = App.Vector(-40.9850, 60.4418, 0)
	P144 = App.Vector(-42.2217, 61.2644, 0)
	S083 = Part.Arc(P142, P143, P144)
	P145 = App.Vector(-42.5598, 61.7549, 0)
	S084 = Part.LineSegment(P144, P145)
	P146 = App.Vector(-43.1467, 62.4984, 0)
	P147 = App.Vector(-43.8248, 63.1598, 0)
	S085 = Part.Arc(P145, P146, P147)
	P148 = App.Vector(-45.2987, 64.3414, 0)
	P149 = App.Vector(-46.8460, 65.4252, 0)
	S086 = Part.Arc(P147, P148, P149)
	P150 = App.Vector(-50.1162, 67.3178, 0)
	P151 = App.Vector(-53.5713, 68.8468, 0)
	S087 = Part.Arc(P149, P150, P151)
	P152 = App.Vector(-58.0522, 70.3290, 0)
	P153 = App.Vector(-62.6442, 71.4192, 0)
	S088 = Part.Arc(P151, P152, P153)
	P154 = App.Vector(-65.3345, 68.9667, 0)
	S089 = Part.LineSegment(P153, P154)
	P155 = App.Vector(-64.6726, 64.2937, 0)
	P156 = App.Vector(-63.6102, 59.6952, 0)
	S090 = Part.Arc(P154, P155, P156)
	P157 = App.Vector(-62.4065, 56.1137, 0)
	P158 = App.Vector(-60.8237, 52.6828, 0)
	S091 = Part.Arc(P156, P157, P158)
	P159 = App.Vector(-59.8873, 51.0421, 0)
	P160 = App.Vector(-58.8467, 49.4655, 0)
	S092 = Part.Arc(P158, P159, P160)
	P161 = App.Vector(-58.2507, 48.7293, 0)
	P162 = App.Vector(-57.5645, 48.0763, 0)
	S093 = Part.Arc(P160, P161, P162)
	P163 = App.Vector(-57.1073, 47.6944, 0)
	S094 = Part.LineSegment(P162, P163)
	P164 = App.Vector(-56.4023, 46.3870, 0)
	P165 = App.Vector(-56.7933, 44.9541, 0)
	S095 = Part.Arc(P163, P164, P165)
	P166 = App.Vector(-58.7802, 42.3230, 0)
	S096 = Part.LineSegment(P165, P166)
	P167 = App.Vector(-60.0515, 41.5548, 0)
	P168 = App.Vector(-61.5018, 41.8751, 0)
	S097 = Part.Arc(P166, P167, P168)
	P169 = App.Vector(-61.9943, 42.2103, 0)
	S098 = Part.LineSegment(P168, P169)
	P170 = App.Vector(-62.8101, 42.6916, 0)
	P171 = App.Vector(-63.6813, 43.0634, 0)
	S099 = Part.Arc(P169, P170, P171)
	P172 = App.Vector(-65.4826, 43.6328, 0)
	P173 = App.Vector(-67.3169, 44.0845, 0)
	S100 = Part.Arc(P171, P172, P173)
	P174 = App.Vector(-71.0499, 44.6679, 0)
	P175 = App.Vector(-74.8241, 44.8456, 0)
	S101 = Part.Arc(P173, P174, P175)
	P176 = App.Vector(-79.5378, 44.6090, 0)
	P177 = App.Vector(-84.2136, 43.9667, 0)
	S102 = Part.Arc(P175, P176, P177)
	P178 = App.Vector(-85.8362, 40.7080, 0)
	S103 = Part.LineSegment(P177, P178)
	P179 = App.Vector(-83.5310, 36.5896, 0)
	P180 = App.Vector(-80.8791, 32.6854, 0)
	S104 = Part.Arc(P178, P179, P180)
	P181 = App.Vector(-78.4629, 29.7806, 0)
	P182 = App.Vector(-75.7476, 27.1532, 0)
	S105 = Part.Arc(P180, P181, P182)
	P183 = App.Vector(-74.2818, 25.9616, 0)
	P184 = App.Vector(-72.7419, 24.8673, 0)
	S106 = Part.Arc(P182, P183, P184)
	P185 = App.Vector(-71.9202, 24.3961, 0)
	P186 = App.Vector(-71.0445, 24.0351, 0)
	S107 = Part.Arc(P184, P185, P186)
	P187 = App.Vector(-70.4802, 23.8442, 0)
	S108 = Part.LineSegment(P186, P187)
	P188 = App.Vector(-69.3505, 22.8797, 0)
	P189 = App.Vector(-69.1974, 21.4023, 0)
	S109 = Part.Arc(P187, P188, P189)
	P190 = App.Vector(-70.0997, 18.2311, 0)
	S110 = Part.LineSegment(P189, P190)
	P191 = App.Vector(-71.0076, 17.0556, 0)
	P192 = App.Vector(-72.4758, 16.8303, 0)
	S111 = Part.Arc(P190, P191, P192)
	P193 = App.Vector(-73.0561, 16.9651, 0)
	S112 = Part.LineSegment(P192, P193)
	P194 = App.Vector(-73.9907, 17.1191, 0)
	P195 = App.Vector(-74.9374, 17.1511, 0)
	S113 = Part.Arc(P193, P194, P195)
	P196 = App.Vector(-76.8227, 17.0313, 0)
	P197 = App.Vector(-78.6963, 16.7899, 0)
	S114 = Part.Arc(P195, P196, P197)
	P198 = App.Vector(-82.3880, 15.9854, 0)
	P199 = App.Vector(-85.9715, 14.7877, 0)
	S115 = Part.Arc(P197, P198, P199)
	P200 = App.Vector(-90.2814, 12.8643, 0)
	P201 = App.Vector(-94.4094, 10.5763, 0)
	S116 = Part.Arc(P199, P200, P201)
	P202 = App.Vector(-94.7453, 6.9515, 0)
	S117 = Part.LineSegment(P201, P202)
	P203 = App.Vector(-91.1080, 3.9439, 0)
	P204 = App.Vector(-87.2249, 1.2613, 0)
	S118 = Part.Arc(P202, P203, P204)
	P205 = App.Vector(-83.9225, -0.5745, 0)
	P206 = App.Vector(-80.4414, -2.0436, 0)
	S119 = Part.Arc(P204, P205, P206)
	P207 = App.Vector(-78.6441, -2.6252, 0)
	P208 = App.Vector(-76.8129, -3.0894, 0)
	S120 = Part.Arc(P206, P207, P208)
	P209 = App.Vector(-75.8765, -3.2319, 0)
	P210 = App.Vector(-74.9295, -3.2522, 0)
	S121 = Part.Arc(P208, P209, P210)
	P211 = App.Vector(-74.3343, -3.2263, 0)
	S122 = Part.LineSegment(P210, P211)
	P212 = App.Vector(-72.9325, -3.7176, 0)
	P213 = App.Vector(-72.2561, -5.0399, 0)
	S123 = Part.Arc(P211, P212, P213)
	P214 = App.Vector(-71.9519, -8.3229, 0)
	S124 = Part.LineSegment(P213, P214)
	P215 = App.Vector(-72.3738, -9.7470, 0)
	P216 = App.Vector(-73.6615, -10.4875, 0)
	S125 = Part.Arc(P214, P215, P216)
	P217 = App.Vector(-74.2512, -10.5714, 0)
	S126 = Part.LineSegment(P216, P217)
	P218 = App.Vector(-75.1784, -10.7654, 0)
	P219 = App.Vector(-76.0727, -11.0776, 0)
	S127 = Part.Arc(P217, P218, P219)
	P220 = App.Vector(-77.7874, -11.8703, 0)
	P221 = App.Vector(-79.4473, -12.7723, 0)
	S128 = Part.Arc(P219, P220, P221)
	P222 = App.Vector(-82.5991, -14.8560, 0)
	P223 = App.Vector(-85.5079, -17.2674, 0)
	S129 = Part.Arc(P221, P222, P223)
	P224 = App.Vector(-88.8320, -20.6178, 0)
	P225 = App.Vector(-91.8548, -24.2425, 0)
	S130 = Part.Arc(P223, P224, P225)
	P226 = App.Vector(-90.8586, -27.7439, 0)
	S131 = Part.LineSegment(P225, P226)
	P227 = App.Vector(-86.3804, -29.2344, 0)
	P228 = App.Vector(-81.7904, -30.3331, 0)
	S132 = Part.Arc(P226, P227, P228)
	P229 = App.Vector(-78.0479, -30.8520, 0)
	P230 = App.Vector(-74.2712, -30.9644, 0)
	S133 = Part.Arc(P228, P229, P230)
	P231 = App.Vector(-72.3851, -30.8575, 0)
	P232 = App.Vector(-70.5099, -30.6288, 0)
	S134 = Part.Arc(P230, P231, P232)
	P233 = App.Vector(-69.5852, -30.4234, 0)
	P234 = App.Vector(-68.6948, -30.1002, 0)
	S135 = Part.Arc(P232, P233, P234)
	P235 = App.Vector(-68.1492, -29.8611, 0)
	S136 = Part.LineSegment(P234, P235)
	P236 = App.Vector(-66.6646, -29.8128, 0)
	P237 = App.Vector(-65.5562, -30.8015, 0)
	S137 = Part.Arc(P235, P236, P237)
	P238 = App.Vector(-64.0866, -33.7529, 0)
	S138 = Part.LineSegment(P237, P238)
	P239 = App.Vector(-63.9656, -35.2333, 0)
	P240 = App.Vector(-64.8987, -36.3889, 0)
	S139 = Part.Arc(P238, P239, P240)
	P241 = App.Vector(-65.4184, -36.6802, 0)
	S140 = Part.LineSegment(P240, P241)
	P242 = App.Vector(-66.2128, -37.1960, 0)
	P243 = App.Vector(-66.9340, -37.8102, 0)
	S141 = Part.Arc(P241, P242, P243)
	P244 = App.Vector(-68.2466, -39.1688, 0)
	P245 = App.Vector(-69.4685, -40.6095, 0)
	S142 = Part.Arc(P243, P244, P245)
	P246 = App.Vector(-71.6547, -43.6911, 0)
	P247 = App.Vector(-73.4961, -46.9904, 0)
	S143 = Part.Arc(P245, P246, P247)
	P248 = App.Vector(-75.3854, -51.3154, 0)
	P249 = App.Vector(-76.8946, -55.7873, 0)
	S144 = Part.Arc(P247, P248, P249)
	P250 = App.Vector(-74.7008, -58.6923, 0)
	S145 = Part.LineSegment(P249, P250)
	P251 = App.Vector(-69.9867, -58.4645, 0)
	P252 = App.Vector(-65.3097, -57.8309, 0)
	S146 = Part.Arc(P250, P251, P252)
	P253 = App.Vector(-61.6324, -56.9627, 0)
	P254 = App.Vector(-58.0702, -55.7033, 0)
	S147 = Part.Arc(P252, P253, P254)
	P255 = App.Vector(-56.3501, -54.9223, 0)
	P256 = App.Vector(-54.6841, -54.0316, 0)
	S148 = Part.Arc(P254, P255, P256)
	P257 = App.Vector(-53.8961, -53.5060, 0)
	P258 = App.Vector(-53.1826, -52.8830, 0)
	S149 = Part.Arc(P256, P257, P258)
	P259 = App.Vector(-52.7601, -52.4630, 0)
	S150 = Part.LineSegment(P258, P259)
	P260 = App.Vector(-51.3933, -51.8817, 0)
	P261 = App.Vector(-50.0025, -52.4032, 0)
	S151 = Part.Arc(P259, P260, P261)
	P262 = App.Vector(-47.5660, -54.6244, 0)
	S152 = Part.LineSegment(P261, P262)
	P263 = App.Vector(-46.9184, -55.9611, 0)
	P264 = App.Vector(-47.3711, -57.3757, 0)
	S153 = Part.Arc(P262, P263, P264)
	P265 = App.Vector(-47.7504, -57.8351, 0)
	S154 = Part.LineSegment(P264, P265)
	P266 = App.Vector(-48.3049, -58.6031, 0)
	P267 = App.Vector(-48.7555, -59.4363, 0)
	S155 = Part.Arc(P265, P266, P267)
	P268 = App.Vector(-49.4886, -61.1773, 0)
	P269 = App.Vector(-50.1076, -62.9621, 0)
	S156 = Part.Arc(P267, P268, P269)
	P270 = App.Vector(-51.0330, -66.6254, 0)
	P271 = App.Vector(-51.5582, -70.3671, 0)
	S157 = Part.Arc(P269, P270, P271)
	P272 = App.Vector(-51.7575, -75.0825, 0)
	P273 = App.Vector(-51.5494, -79.7976, 0)
	S158 = Part.Arc(P271, P272, P273)
	P274 = App.Vector(-48.4543, -81.7140, 0)
	S159 = Part.LineSegment(P273, P274)
	P275 = App.Vector(-44.1408, -79.7986, 0)
	P276 = App.Vector(-40.0086, -77.5183, 0)
	S160 = Part.Arc(P274, P275, P276)
	P277 = App.Vector(-36.8932, -75.3804, 0)
	P278 = App.Vector(-34.0265, -72.9191, 0)
	S161 = Part.Arc(P276, P277, P278)
	P279 = App.Vector(-32.7047, -71.5695, 0)
	P280 = App.Vector(-31.4730, -70.1371, 0)
	S162 = Part.Arc(P278, P279, P280)
	P281 = App.Vector(-30.9280, -69.3624, 0)
	P282 = App.Vector(-30.4877, -68.5237, 0)
	S163 = Part.Arc(P280, P281, P282)
	P283 = App.Vector(-30.2455, -67.9794, 0)
	S164 = Part.LineSegment(P282, P283)
	P284 = App.Vector(-29.1810, -66.9436, 0)
	P285 = App.Vector(-27.6958, -66.9275, 0)
	S165 = Part.Arc(P283, P284, P285)
	P286 = App.Vector(-24.6214, -68.1185, 0)
	S166 = Part.LineSegment(P285, P286)
	P287 = App.Vector(-23.5346, -69.1310, 0)
	P288 = App.Vector(-23.4457, -70.6137, 0)
	S167 = Part.Arc(P286, P287, P288)
	P289 = App.Vector(-23.6334, -71.1791, 0)
	S168 = Part.LineSegment(P288, P289)
	P290 = App.Vector(-23.8731, -72.0955, 0)
	P291 = App.Vector(-23.9923, -73.0352, 0)
	S169 = Part.Arc(P289, P290, P291)
	P292 = App.Vector(-24.0470, -74.9235, 0)
	P293 = App.Vector(-23.9794, -76.8114, 0)
	S170 = Part.Arc(P291, P292, P293)
	P294 = App.Vector(-23.5190, -80.5616, 0)
	P295 = App.Vector(-22.6570, -84.2403, 0)
	S171 = Part.Arc(P293, P294, P295)
	P296 = App.Vector(-21.1395, -88.7093, 0)
	P297 = App.Vector(-19.2422, -93.0308, 0)
	S172 = Part.Arc(P295, P296, P297)
	P298 = App.Vector(-15.6638, -93.6998, 0)
	S173 = Part.LineSegment(P297, P298)
	P299 = App.Vector(-12.3335, -90.3555, 0)
	P300 = App.Vector(-9.3041, -86.7364, 0)
	S174 = Part.Arc(P298, P299, P300)
	P301 = App.Vector(-7.1714, -83.6175, 0)
	P302 = App.Vector(-5.3873, -80.2868, 0)
	S175 = Part.Arc(P300, P301, P302)
	P303 = App.Vector(-4.6423, -78.5509, 0)
	P304 = App.Vector(-4.0112, -76.7703, 0)
	S176 = Part.Arc(P302, P303, P304)
	P305 = App.Vector(-3.7829, -75.8510, 0)
	P306 = App.Vector(-3.6753, -74.9099, 0)
	S177 = Part.Arc(P304, P305, P306)
	P307 = App.Vector(-3.6461, -74.3149, 0)
	S178 = Part.LineSegment(P306, P307)
	P308 = App.Vector(-3.0276, -72.9644, 0)
	P309 = App.Vector(-1.6485, -72.4129, 0)
	S179 = Part.Arc(P307, P308, P309)
	P310 = App.Vector(1.6485, -72.4129, 0)
	S180 = Part.LineSegment(P309, P310)
	P311 = App.Vector(3.0276, -72.9644, 0)
	P312 = App.Vector(3.6461, -74.3149, 0)
	S181 = Part.Arc(P310, P311, P312)
	P313 = App.Vector(3.6753, -74.9099, 0)
	S182 = Part.LineSegment(P312, P313)
	P314 = App.Vector(3.7829, -75.8510, 0)
	P315 = App.Vector(4.0112, -76.7703, 0)
	S183 = Part.Arc(P313, P314, P315)
	P316 = App.Vector(4.6423, -78.5509, 0)
	P317 = App.Vector(5.3873, -80.2868, 0)
	S184 = Part.Arc(P315, P316, P317)
	P318 = App.Vector(7.1714, -83.6175, 0)
	P319 = App.Vector(9.3041, -86.7364, 0)
	S185 = Part.Arc(P317, P318, P319)
	P320 = App.Vector(12.3335, -90.3555, 0)
	P321 = App.Vector(15.6638, -93.6998, 0)
	S186 = Part.Arc(P319, P320, P321)
	P322 = App.Vector(19.2422, -93.0308, 0)
	S187 = Part.LineSegment(P321, P322)
	P323 = App.Vector(21.1395, -88.7093, 0)
	P324 = App.Vector(22.6570, -84.2403, 0)
	S188 = Part.Arc(P322, P323, P324)
	P325 = App.Vector(23.5190, -80.5616, 0)
	P326 = App.Vector(23.9794, -76.8114, 0)
	S189 = Part.Arc(P324, P325, P326)
	P327 = App.Vector(24.0470, -74.9235, 0)
	P328 = App.Vector(23.9923, -73.0352, 0)
	S190 = Part.Arc(P326, P327, P328)
	P329 = App.Vector(23.8731, -72.0955, 0)
	P330 = App.Vector(23.6334, -71.1791, 0)
	S191 = Part.Arc(P328, P329, P330)
	P331 = App.Vector(23.4457, -70.6137, 0)
	S192 = Part.LineSegment(P330, P331)
	P332 = App.Vector(23.5346, -69.1310, 0)
	P333 = App.Vector(24.6214, -68.1185, 0)
	S193 = Part.Arc(P331, P332, P333)
	P334 = App.Vector(27.6958, -66.9275, 0)
	S194 = Part.LineSegment(P333, P334)
	P335 = App.Vector(29.1810, -66.9436, 0)
	P336 = App.Vector(30.2455, -67.9794, 0)
	S195 = Part.Arc(P334, P335, P336)
	P337 = App.Vector(30.4877, -68.5237, 0)
	S196 = Part.LineSegment(P336, P337)
	P338 = App.Vector(30.9280, -69.3624, 0)
	P339 = App.Vector(31.4730, -70.1371, 0)
	S197 = Part.Arc(P337, P338, P339)
	P340 = App.Vector(32.7047, -71.5695, 0)
	P341 = App.Vector(34.0265, -72.9191, 0)
	S198 = Part.Arc(P339, P340, P341)
	P342 = App.Vector(36.8932, -75.3804, 0)
	P343 = App.Vector(40.0086, -77.5183, 0)
	S199 = Part.Arc(P341, P342, P343)
	P344 = App.Vector(44.1408, -79.7986, 0)
	P345 = App.Vector(48.4543, -81.7140, 0)
	S200 = Part.Arc(P343, P344, P345)
	P346 = App.Vector(51.5494, -79.7976, 0)
	S201 = Part.LineSegment(P345, P346)
	P347 = App.Vector(51.7575, -75.0825, 0)
	P348 = App.Vector(51.5582, -70.3671, 0)
	S202 = Part.Arc(P346, P347, P348)
	P349 = App.Vector(51.0330, -66.6254, 0)
	P350 = App.Vector(50.1076, -62.9621, 0)
	S203 = Part.Arc(P348, P349, P350)
	P351 = App.Vector(49.4886, -61.1773, 0)
	P352 = App.Vector(48.7555, -59.4363, 0)
	S204 = Part.Arc(P350, P351, P352)
	P353 = App.Vector(48.3049, -58.6031, 0)
	P354 = App.Vector(47.7504, -57.8351, 0)
	S205 = Part.Arc(P352, P353, P354)
	P355 = App.Vector(47.3711, -57.3757, 0)
	S206 = Part.LineSegment(P354, P355)
	P356 = App.Vector(46.9184, -55.9611, 0)
	P357 = App.Vector(47.5660, -54.6244, 0)
	S207 = Part.Arc(P355, P356, P357)
	P358 = App.Vector(50.0025, -52.4032, 0)
	S208 = Part.LineSegment(P357, P358)
	P359 = App.Vector(51.3933, -51.8817, 0)
	P360 = App.Vector(52.7601, -52.4630, 0)
	S209 = Part.Arc(P358, P359, P360)
	P361 = App.Vector(53.1826, -52.8830, 0)
	S210 = Part.LineSegment(P360, P361)
	P362 = App.Vector(53.8961, -53.5060, 0)
	P363 = App.Vector(54.6841, -54.0316, 0)
	S211 = Part.Arc(P361, P362, P363)
	P364 = App.Vector(56.3501, -54.9223, 0)
	P365 = App.Vector(58.0702, -55.7033, 0)
	S212 = Part.Arc(P363, P364, P365)
	P366 = App.Vector(61.6324, -56.9627, 0)
	P367 = App.Vector(65.3097, -57.8309, 0)
	S213 = Part.Arc(P365, P366, P367)
	P368 = App.Vector(69.9867, -58.4645, 0)
	P369 = App.Vector(74.7008, -58.6923, 0)
	S214 = Part.Arc(P367, P368, P369)
	P370 = App.Vector(76.8946, -55.7873, 0)
	S215 = Part.LineSegment(P369, P370)
	P371 = App.Vector(75.3854, -51.3154, 0)
	P372 = App.Vector(73.4961, -46.9904, 0)
	S216 = Part.Arc(P370, P371, P372)
	P373 = App.Vector(71.6547, -43.6911, 0)
	P374 = App.Vector(69.4685, -40.6095, 0)
	S217 = Part.Arc(P372, P373, P374)
	P375 = App.Vector(68.2466, -39.1688, 0)
	P376 = App.Vector(66.9340, -37.8102, 0)
	S218 = Part.Arc(P374, P375, P376)
	P377 = App.Vector(66.2128, -37.1960, 0)
	P378 = App.Vector(65.4184, -36.6802, 0)
	S219 = Part.Arc(P376, P377, P378)
	P379 = App.Vector(64.8987, -36.3889, 0)
	S220 = Part.LineSegment(P378, P379)
	P380 = App.Vector(63.9656, -35.2333, 0)
	P381 = App.Vector(64.0866, -33.7529, 0)
	S221 = Part.Arc(P379, P380, P381)
	P382 = App.Vector(65.5562, -30.8015, 0)
	S222 = Part.LineSegment(P381, P382)
	P383 = App.Vector(66.6646, -29.8128, 0)
	P384 = App.Vector(68.1492, -29.8611, 0)
	S223 = Part.Arc(P382, P383, P384)
	P385 = App.Vector(68.6948, -30.1002, 0)
	S224 = Part.LineSegment(P384, P385)
	P386 = App.Vector(69.5852, -30.4234, 0)
	P387 = App.Vector(70.5099, -30.6288, 0)
	S225 = Part.Arc(P385, P386, P387)
	P388 = App.Vector(72.3851, -30.8575, 0)
	P389 = App.Vector(74.2712, -30.9644, 0)
	S226 = Part.Arc(P387, P388, P389)
	P390 = App.Vector(78.0479, -30.8520, 0)
	P391 = App.Vector(81.7904, -30.3331, 0)
	S227 = Part.Arc(P389, P390, P391)
	P392 = App.Vector(86.3804, -29.2344, 0)
	P393 = App.Vector(90.8586, -27.7439, 0)
	S228 = Part.Arc(P391, P392, P393)
	P394 = App.Vector(91.8548, -24.2425, 0)
	S229 = Part.LineSegment(P393, P394)
	P395 = App.Vector(88.8320, -20.6178, 0)
	P396 = App.Vector(85.5079, -17.2674, 0)
	S230 = Part.Arc(P394, P395, P396)
	P397 = App.Vector(82.5991, -14.8560, 0)
	P398 = App.Vector(79.4473, -12.7723, 0)
	S231 = Part.Arc(P396, P397, P398)
	P399 = App.Vector(77.7874, -11.8703, 0)
	P400 = App.Vector(76.0727, -11.0776, 0)
	S232 = Part.Arc(P398, P399, P400)
	P401 = App.Vector(75.1784, -10.7654, 0)
	P402 = App.Vector(74.2512, -10.5714, 0)
	S233 = Part.Arc(P400, P401, P402)
	P403 = App.Vector(73.6615, -10.4875, 0)
	S234 = Part.LineSegment(P402, P403)
	P404 = App.Vector(72.3738, -9.7470, 0)
	P405 = App.Vector(71.9519, -8.3229, 0)
	S235 = Part.Arc(P403, P404, P405)
	P406 = App.Vector(72.2561, -5.0399, 0)
	S236 = Part.LineSegment(P405, P406)
	P407 = App.Vector(72.9325, -3.7176, 0)
	P408 = App.Vector(74.3343, -3.2263, 0)
	S237 = Part.Arc(P406, P407, P000)
	aShape = Part.Shape([S000, S001, S002, S003, S004, S005, S006, S007, S008, S009, S010, S011, S012, S013, S014, S015, S016, S017, S018, S019, S020, S021, S022, S023, S024, S025, S026, S027, S028, S029, S030, S031, S032, S033, S034, S035, S036, S037, S038, S039, S040, S041, S042, S043, S044, S045, S046, S047, S048, S049, S050, S051, S052, S053, S054, S055, S056, S057, S058, S059, S060, S061, S062, S063, S064, S065, S066, S067, S068, S069, S070, S071, S072, S073, S074, S075, S076, S077, S078, S079, S080, S081, S082, S083, S084, S085, S086, S087, S088, S089, S090, S091, S092, S093, S094, S095, S096, S097, S098, S099, S100, S101, S102, S103, S104, S105, S106, S107, S108, S109, S110, S111, S112, S113, S114, S115, S116, S117, S118, S119, S120, S121, S122, S123, S124, S125, S126, S127, S128, S129, S130, S131, S132, S133, S134, S135, S136, S137, S138, S139, S140, S141, S142, S143, S144, S145, S146, S147, S148, S149, S150, S151, S152, S153, S154, S155, S156, S157, S158, S159, S160, S161, S162, S163, S164, S165, S166, S167, S168, S169, S170, S171, S172, S173, S174, S175, S176, S177, S178, S179, S180, S181, S182, S183, S184, S185, S186, S187, S188, S189, S190, S191, S192, S193, S194, S195, S196, S197, S198, S199, S200, S201, S202, S203, S204, S205, S206, S207, S208, S209, S210, S211, S212, S213, S214, S215, S216, S217, S218, S219, S220, S221, S222, S223, S224, S225, S226, S227, S228, S229, S230, S231, S232, S233, S234, S235, S236, S237])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def ctr_face_gear_wheel_teethProfile_Fa0_Ctr1():
	P000 = App.Vector(16.0000, 4.0000, 0)
	P001 = App.Vector(10.3923, 4.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(9.3923, 4.2679, 0)
	P003 = App.Vector(8.6603, 5.0000, 0)
	S001 = Part.Arc(P001, P002, P003)
	P004 = App.Vector(-10.0000, 0.0000, 0)
	P005 = App.Vector(8.6603, -5.0000, 0)
	S002 = Part.Arc(P003, P004, P005)
	P006 = App.Vector(9.3923, -4.2679, 0)
	P007 = App.Vector(10.3923, -4.0000, 0)
	S003 = Part.Arc(P005, P006, P007)
	P008 = App.Vector(16.0000, -4.0000, 0)
	S004 = Part.LineSegment(P007, P008)
	P009 = App.Vector(17.4142, -3.4142, 0)
	P010 = App.Vector(18.0000, -2.0000, 0)
	S005 = Part.Arc(P008, P009, P010)
	P011 = App.Vector(18.0000, 2.0000, 0)
	S006 = Part.LineSegment(P010, P011)
	P012 = App.Vector(17.4142, 3.4142, 0)
	P013 = App.Vector(16.0000, 4.0000, 0)
	S007 = Part.Arc(P011, P012, P000)
	aShape = Part.Shape([S000, S001, S002, S003, S004, S005, S006, S007])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def ctr_face_gear_wheel_teethProfile_Fa0_Ctr2():
	P000 = App.Vector(51.0028, 12.4485, 0)
	P001 = App.Vector(-52.5000, 0.0000, 0)
	P002 = App.Vector(51.0028, -12.4485, 0)
	S000 = Part.Arc(P000, P001, P002)
	P003 = App.Vector(50.2628, -9.0296, 0)
	P004 = App.Vector(47.1169, -7.5000, 0)
	S001 = Part.Arc(P002, P003, P004)
	P005 = App.Vector(24.4285, -7.5000, 0)
	S002 = Part.LineSegment(P004, P005)
	P006 = App.Vector(22.2854, -8.1225, 0)
	P007 = App.Vector(20.8094, -9.7963, 0)
	S003 = Part.Arc(P005, P006, P007)
	P008 = App.Vector(-23.0000, 0.0000, 0)
	P009 = App.Vector(20.8094, 9.7963, 0)
	S004 = Part.Arc(P007, P008, P009)
	P010 = App.Vector(22.2854, 8.1225, 0)
	P011 = App.Vector(24.4285, 7.5000, 0)
	S005 = Part.Arc(P009, P010, P011)
	P012 = App.Vector(47.1169, 7.5000, 0)
	S006 = Part.LineSegment(P011, P012)
	P013 = App.Vector(50.2628, 9.0296, 0)
	P014 = App.Vector(51.0028, 12.4485, 0)
	S007 = Part.Arc(P012, P013, P000)
	aShape = Part.Shape([S000, S001, S002, S003, S004, S005, S006, S007])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_gear_wheel_teethProfile_Fa0():
	FC000 = ctr_face_gear_wheel_teethProfile_Fa0_Ctr0()
	FC001 = ctr_face_gear_wheel_teethProfile_Fa0_Ctr1()
	FC002 = ctr_face_gear_wheel_teethProfile_Fa0_Ctr2()
	rOneFace = FC000.cut([FC001, FC002])
	rOneFace.check()
	return rOneFace

def gear_wheel_teethProfile():
	FA000 = face_gear_wheel_teethProfile_Fa0()
	rOneFig = FA000
	rOneFig.check()
	return rOneFig

def ctr_face_gear_wheel_axisProfile_Fa0_Ctr0():
	P000 = App.Vector(0.0000, -66.0000, 0)
	P001 = App.Vector(16.0000, -66.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(18.8284, -64.8284, 0)
	P003 = App.Vector(20.0000, -62.0000, 0)
	S001 = Part.Arc(P001, P002, P003)
	P004 = App.Vector(20.0000, -26.0000, 0)
	S002 = Part.LineSegment(P003, P004)
	P005 = App.Vector(60.0000, -26.0000, 0)
	S003 = Part.LineSegment(P004, P005)
	P006 = App.Vector(92.6576, -20.5571, 0)
	S004 = Part.LineSegment(P005, P006)
	P007 = App.Vector(95.0521, -19.1970, 0)
	P008 = App.Vector(96.0000, -16.6115, 0)
	S005 = Part.Arc(P006, P007, P008)
	P009 = App.Vector(96.0000, 16.6115, 0)
	S006 = Part.LineSegment(P008, P009)
	P010 = App.Vector(95.0521, 19.1970, 0)
	P011 = App.Vector(92.6576, 20.5571, 0)
	S007 = Part.Arc(P009, P010, P011)
	P012 = App.Vector(60.0000, 26.0000, 0)
	S008 = Part.LineSegment(P011, P012)
	P013 = App.Vector(20.0000, 26.0000, 0)
	S009 = Part.LineSegment(P012, P013)
	P014 = App.Vector(20.0000, 62.0000, 0)
	S010 = Part.LineSegment(P013, P014)
	P015 = App.Vector(18.8284, 64.8284, 0)
	P016 = App.Vector(16.0000, 66.0000, 0)
	S011 = Part.Arc(P014, P015, P016)
	P017 = App.Vector(0.0000, 66.0000, 0)
	S012 = Part.LineSegment(P016, P017)
	P018 = App.Vector(0.0000, -66.0000, 0)
	S013 = Part.LineSegment(P017, P000)
	aShape = Part.Shape([S000, S001, S002, S003, S004, S005, S006, S007, S008, S009, S010, S011, S012, S013])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_gear_wheel_axisProfile_Fa0():
	FC000 = ctr_face_gear_wheel_axisProfile_Fa0_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def gear_wheel_axisProfile():
	FA000 = face_gear_wheel_axisProfile_Fa0()
	rOneFig = FA000
	rOneFig.check()
	return rOneFig

def fex_subpax_gear_wheel_teethProfile():
	FIG = gear_wheel_teethProfile()
	VEX = FIG.extrude(App.Vector(0, 0, 152))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 0.0000)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 0.0000)
	VFP = VR3.translate(App.Vector(0.0000, 0.0000, -76.0000))
	return VFP
subpax_gear_wheel_teethProfile = fex_subpax_gear_wheel_teethProfile()

def fex_subpax_gear_wheel_axisProfile():
	FIG = gear_wheel_axisProfile()
	VEX = FIG.revolve(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 360).rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 90)
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 0.0000)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 0.0000)
	VFP = VR3.translate(App.Vector(0.0000, 0.0000, 0.0000))
	return VFP
subpax_gear_wheel_axisProfile = fex_subpax_gear_wheel_axisProfile()

def fvol_pax_gear_wheel():
	V000 = subpax_gear_wheel_teethProfile
	V001 = V000.common(subpax_gear_wheel_axisProfile)
	VFC = V001.removeSplitter()
	return VFC
pax_gear_wheel = fvol_pax_gear_wheel()


pax_gear_wheel.check()
#pax_gear_wheel.exportBrep(f"{outFileName}.brep")
#pax_gear_wheel.exportIges(f"{outFileName}.igs")
#pax_gear_wheel.exportStep(f"{outFileName}.stp")
pax_gear_wheel.exportStl(f"{outFileName}.stl")

